name: "Broken Link Checker"
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: corepack enable
      - name: Get Vercel Preview URL
        id: vercelDeployment
        uses: mishkeTz/get-vercel-preview-url-by-project-id@main
        with:
          vercel_access_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - id: runLinkChecker
        name: "Run link checker"
        continue-on-error: true
        env:
          PREVIEW_URL: ${{ steps.vercelDeployment.outputs.preview_url }}
        run: |
          {
            echo 'OUTPUT<<EOF'
            echo "$(pnpx broken-link-checker -f -r "$PREVIEW_URL")"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Comment results on PR
        uses: actions/github-script@v7
        env:
          CHECKER_OUTPUT: ${{ steps.runLinkChecker.outputs.OUTPUT }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1a. Retrieve PRs
            let prNumber = undefined
            if (context.payload.number) {
              // From trigger:pull_request
              prNumber = context.payload.number
            } else {
              // From trigger:push
              const { data: pulls } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${context.ref.replace('refs/heads/','')}`
              })
              prNumber = pulls[0]?.number
            }

            if (prNumber) {
              // 1b. Retrieve existing bot comments for the PR
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
              });

              const headline = `## Link Checker Results`
              const data = process.env.CHECKER_OUTPUT
              const output = `${headline}

              ${data}`

              const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes(headline)
              });

              // 3. Update previous comment so we have edit timeline
              if (botComment) {
                github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: output,
                });
              } else {
                github.rest.issues.createComment({
                  issue_number: prNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output,
                });
              }
            }
